[theme] # This line is necessary

# Defines the accent color
primaryColor = '#3bcfe3' # Dark Grey

# Background color of the main content area
backgroundColor = '#FFFFFF' # White

# Second background color for added contrast
secondaryBackgroundColor = '#3bcfe3' # Dark Blue

textColor = '#333E36' # Dark

font = "serif"
