[theme] # This line is necessary

# Defines the accent color
primaryColor = '#FF8C02' # Bright Orange

# Background color of the main content area
backgroundColor = '#333E36' # Dark

# Second background color for added contrast
secondaryBackgroundColor = '#2B74C1' # Dark Blue

textColor = '#FFFFFF' # White

font = "serif"
